# Фінальний проект "Населення"

### Виконує:

#### Онищенко Богдан \ Onyshchenko Bohdan \ vumenira

In [1]:
import pandas as pd
import altair as alt

## Частина 1: Підготовка даних

In [3]:
people_1897 = pd.read_csv("2.1_Дунаєць.xlsx - База людей.csv")
#people_1778

people_1778 = pd.read_csv("2.2_Дунаєць_1778.xlsx - База.csv")

people_1778

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Аркуш,NaN,NaN,NaN,Число людей наскрізне,NaN,Число людей джерело,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,ID наскрізна,ID домогосподарство,Двори джерело,Чоловіки,Жінки,Чоловіки,Жінки,Імʼя,По-батькові,Прізвище,Родиний статус,Категорія,Клас,Соціальний статус,Вік,Був на сповіді,Не був,Не був за малолітством
3,445,1,1,1,1,NaN,1,NaN,Федор,Кондратьев,Лукашевич,господар,nuclear,3b,духовные,44,х,NaN,NaN
4,NaN,2,NaN,NaN,NaN,1,NaN,1,Варвара,Симева,NaN,жена,NaN,NaN,духовные,35,х,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,NaN,1593,104,12,824,NaN,236,NaN,Леонтий,Афанасиев,NaN,двоюродный брат Александра,nuclear,3a,бездворные,25,х,NaN,NaN
1596,NaN,1594,NaN,NaN,NaN,770,NaN,222,Мотрона,Михайлова,NaN,жена его,NaN,NaN,бездворные,22,х,NaN,NaN
1597,NaN,1595,105,13,825,NaN,237,NaN,Герасим,Фомик,Мерник,господар,nuclear,3b,бездворные,43,х,NaN,NaN
1598,NaN,1596,NaN,NaN,NaN,771,NaN,223,Агафия,Максимова,NaN,жена его,NaN,NaN,бездворные,42,х,NaN,NaN
1599,NaN,1597,NaN,NaN,826,NaN,238,NaN,Лукьян,NaN,NaN,NaN,NaN,NaN,бездворные,14,х,NaN,NaN